name: CICDLaurentPepin
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
   
  deploy:
    runs-on: ubuntu-latest
    needs: build
      
    steps:
    - name: Paso de Despliegue
      run: echo "Este es el paso de despliegue"
      